### ISSUE TITLE
Ajax implementation takes "happy path" when status === 0

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS-DOM#32]
Status 0 should be an error. If you get back an empty response from a server for whatever reason, status you will receive status code 0, even if the response was sent in error. 

https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/src/ajax.js#L99

Likewise, there's really no circumstance by which a status code of `''` should arrive.

**Comment by mattpodwysocki** [comment]
@blesh 0 is a perfectly valid value for success with regards to Ajax, for file:// queries.  See [xhr.js](https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js#L16-L17) from jQuery.  And the usage of '' comes from the old IE ActiveX control versions of XMLHttpRequest.

**Comment by blesh** [comment]
You're right.

It's probably just a problem with our server implementation then. I was doing some manual testing and sending the server something where I *knew* it (the server) was in a state it shouldn't respond with anything "OK"... and I was getting back status 0 with an empty response. 

I think I've run into this in years passed as well.
