### ISSUE TITLE
jsonpRequest does't behave like a cold Observable

### ISSUE THREAD

**Issue by sergi** [Reactive-Extensions/RxJS-DOM#39]
When subscribing more than one Observer to a `jsonpRequest` Observable, only one of the subscribers will be called back. In the example below only `A` will be ever logged, for example.

    var test = Rx.Observable
      .interval(1000)
      .flatMap(function() {
        return Rx.DOM.jsonpRequest({
          url: https://gist.githubusercontent.com/sergi/8218eadccc167961ba1a/raw/9b23eaf092ca5c7aec65b5b93e1facc5ac1628cf/test_rx_jsonp.json,
          jsonpCallback: 'test_rx_jsonp'
        });
      });

    var A = test.subscribe(function(res) { console.log('A', res) });
    var B = test.subscribe(function(res) { console.log('B', res) });

A workaround is to use `publish` on the Observable, but it shouldn't be necessary.

**Comment by paulpdaniels** [comment]
I don't believe you are actually subscribing to the jsonpRequest multiple times in this example, you are creating two separate streams since flatMap does not share an underlying subscription (which is why publish() works)

What is the rationale behind allowing users to set their own callback name?  It seems highly confusing to me that the 'test_rx_jsonp' callback is sort of floating between parallel Rx streams.

**Comment by sergi** [comment]
The rationale is that there are many `jsonp` resources around that don't allow the developer to set a name for the `jsonp` callback via querystring, and the jsonp file has a hardcoded padding. The developer then has to write a function with the name chosen by the remote resource. In the rxjs case, it can handle these kind of jsonp resources by allowing the developer to pass the name the generated function should have.

Not sure if I made it clear, happy to clarify more!

**Comment by sergi** [comment]
Also, subscribing multiple times or not, both `A` and `B` should be logging data, independently from the fact that they share an underlying subscription or not. In the situation you mention, the two separate streams should still be both logging, but what happens in my example is that only one does.

**Comment by mattpodwysocki** [comment]
@sergi can we close this issue now?

**Comment by mattpodwysocki** [comment]
@sergi redid the JSONP adapter and two observers should just work
