### ISSUE TITLE
Add speech observables

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS-DOM#43]
RxJS is a nice fit, particularly for the SpeechRecognition api.

Here's a fun demo of both speech recognition and synthesis with RxJS (if you have your speakers on, it "hears" itself, LOL): http://jsbin.com/nunije/1/edit?js,output

The SpeechRecognition bit looks like this:

```js
var SpeechRecognition = root.SpeechRecognition ||
                          root.webkitSpeechRecognition ||
                          root.mozSpeechRecognition ||
                          root.msSpeechRecognition ||
                          root.oSpeechRecognition;


function fromSpeechRecognition(options) {
  var config = extend({
    continuous: false,
    maxAlternatives: 5,
    lang: 'en-US'
  }, options);
  
  return Observable.create((obs) => {
    if(!SpeechRecognition) {
      throw new Error('speech recognition not supported');
    }
    
    var recognition = new SpeechRecognition();
    recognition.continuous = config.continuous;
    
    recognition.onresult = (e) => {
      obs.onNext(e);
      //obs.onCompleted();
    };
    
    recognition.onerror = (e) => {
      obs.onError(e);
    };
    
    recognition.onend = (e) => {
      console.log(e);
      obs.onCompleted();
    };
    
    recognition.start();
    
    return () => {
      recognition.stop();
    };
  });
}
```

And the speech synthesis looks like this:

```js
function fromSpeechUtterance(text) {
  return Observable.create((obs) => {
    var msg = new SpeechSynthesisUtterance(text);
    
    speechSynthesis.speak(msg);
    
    msg.onend = (e) => {
      obs.onNext(msg);
      obs.onCompleted();
    }
  });
}
```

**Comment by blesh** [comment]
FYI: `extend` above is just a simple object extension helper.

Also, FWIW: There isn't a really great way to cancel out of a speech Utterance that has already been Queued up with `speechRecognition.speak()`. You can clear the whole queue, but that's really it. So the speech utterance piece would have to manage it's own scheduling of sorts. The above implementation is too primitive for advanced needs.

**Comment by mattpodwysocki** [comment]
@blesh instead of this, we could just add a sample of going to speech.  We added one to the main RxJS repository.
