### ISSUE TITLE
Reusing jsonpRequest settings objects multiple times results errors

### ISSUE THREAD

**Issue by jzvandenoever** [Reactive-Extensions/RxJS-DOM#46]
When doing a jsonpRequest using a settings object as a parameter you can't reuse that settings object or you get a TypeError. Because the url has been changed. And the proper new callback won't be set.

Thus it tries to call a function on the success of the result that is no longer there if one of the previous requests has already been made.

This is undesired behaviour because you might be polling dynamic data that can change over time. Like when requesting real time data and keeping it updated.

This is related to #45 because if the code is incorrect then the fix is solving that issue.

**Comment by jzvandenoever** [comment]
While easy to solve without changing any other behaviour this will be untestable in the current setup for testcases. Since this relies on checking if the url in the settings object gets changed. And using non-existent urls results in GET errors that are uncaught.

**Comment by paulpdaniels** [comment]
So we just need to create a copy of the settings object to avoid changing it yes?

**Comment by jzvandenoever** [comment]
Quite true. Though currently the only side-effect of the function on the settings object is changing the url. So just creating a copy of the url would suffice too.
