### ISSUE TITLE
webpack loading problems

### ISSUE THREAD

**Issue by acthp** [Reactive-Extensions/RxJS-DOM#49]
Trying to bundle with webpack, the AMD loader chokes on requiring './rx', because there's no file rx.js relative to rx.dom.js. This can be worked around with require('imports?define=>false!rx-dom') to disable the AMD loader, but it's clunky.

I note that rx-jquery works because it requires 'rx', not './rx'. Maybe rx-dom should do the same?

**Comment by Willmo36** [comment]
Can you show an example of this please? When I try to require using that method, webpack is throwing an error:

ERROR in ./index.js
Module not found: Error: Cannot resolve module 'imports' in C:\Users\Maxbook\WebstormProjects\Bertha2PoC/app
 @ ./index.js 5:0-39

**Comment by mattpodwysocki** [comment]
@acthp fixed
