### ISSUE TITLE
Message not sent if the socket is not already opened

### ISSUE THREAD

**Issue by Conaclos** [Reactive-Extensions/RxJS-DOM#52]
Hi!

I'm using rx-lite 2.4.7 and the last build of RxJs-Dom.

If I use the first example from [documentation](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/fromwebsocket.md), the message 'test' is never sent to the server.

In contrast, If I wait that the socket be opened, the message is sent.

Best regards.

**Comment by blesh** [comment]
This is by design for now. The socket implementation in Rx-DOM is a basic socket implementation. It doesn't make assumptions about your intentions when it comes to the socket. Some applications might not want to queue messages sent over the socket.

There are two options: 

1. Use [RxSocketSubject](http://github.com/blesh/RxSocketSubject), which wraps Rx-DOM's socket impl, to allow things like ensuring a single instance, queuing messages to be sent prior to connection, and multiplexing.
2. Write your own code/wrapper to handle the queuing of sent items:

```js
var toSend = getAStreamOfMessagesToSend();
var open = new Rx.Subject();
var socket  = Rx.DOM.fromWebSocket('ws://some/url/here', null, open);
// buffer the messages you want to send until open, then flatMap them out,
// then concat the remaining messages to send.
toSend.buffer(open).take(1).flatMap(x => x).concat(toSend).subscribe(socket);

socket.subscritbe(e => console.log('message received: ',  e));
```

**Comment by sod** [comment]
In 5.0.2 `isOpen = true` is never being executed if `openObserver` argument is falsy as of this:
https://github.com/Reactive-Extensions/RxJS-DOM/blob/a1f394f990ce037656205ce7307e3155aafb0dc0/src/websocket.js#L60

So if you forget to pass an `openObserver` a subscriber won't receive any messages, as isOpen stays false.

**Comment by blesh** [comment]
@mattpodwysocki - I think https://github.com/Reactive-Extensions/RxJS-DOM/commit/a1f394f990ce037656205ce7307e3155aafb0dc0 needs to be rolled back, for reasons I've commented on in that commit. The `return obs.onError()` is a good catch, though.

As for this Issue, I don't think Rx.DOM can assume that every author that is using `fromWebSocket` wants the behavior that buffers messages to be sent prior to socket subscription or connection. Using the `openObserver` argument allows authors to do this themselves, or they can use another abstraction, such as RxSocketSubject. It's my opinion (or at least my understanding) that `fromWebSocket` was meant to be a naive and basic implementation of Observable around WebSocket in it's most primitive form.

**Comment by bleathem** [comment]
> This is by design for now. [...] Some applications might not want to queue messages sent over the socket.

This contradicts the [documentation for Rx.DOM.fromWebSocket](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/fromwebsocket.md) which has the example comment:

```
// send a message on the socket
// this will queue until the socket is open.
socket.onNext('test');
```

From the discussion in this issue, it sounds like the example comment should be changed to indicate the message will *not* be queued.  It in fact generates an error:

> Uncaught TypeError: Cannot read property 'readyState' of undefined

**Comment by mattpodwysocki** [comment]
@Conaclos removed the misleading documentation and added a check for if the socket has not yet been created.
