### ISSUE TITLE
Rx.DOM.ajax -- add support for timeout

### ISSUE THREAD

**Issue by randallr** [Reactive-Extensions/RxJS-DOM#71]
Add support for setting timeout on an AJAX request ( e.g. ``Rx.DOM.ajax({ url: '/unresponsive/endpoint', timeout: 10000 })`` ).  Trigger subscription's ``onError()`` when timed out.

**Comment by randallr** [comment]
Suggested tweak is:

![image](https://cloud.githubusercontent.com/assets/373760/8525190/6549ce14-23cd-11e5-9d43-c599b087d7c4.png)

**Comment by paulpdaniels** [comment]
Is there an advantage to doing that over using `Rx.Observable.prototype.timeout`?

**Comment by randallr** [comment]
Good question.  I think your suggesting:

   ```var ajax = Rx.DOM.ajax({ url: '/unresponsive/endpoint' }).timeout(10000)```

This works, but is there a way to distinguish a timeout error from a request error?  The suggested implementation will pass 'timeout' as the error type that you can handle accordingly.

**Comment by mattpodwysocki** [comment]
@randallr closing as I've just added it to the ajax method. Can't hurt to have more options although timeout is just as easy.
