### ISSUE TITLE
Add URL observable

### ISSUE THREAD

**Issue by menelaos** [Reactive-Extensions/RxJS-DOM#77]
Hey, 
would it be possible to add an observable that tracks the URL in the address bar?

**Comment by blesh** [comment]
@menelaos you could just do:

```js
var hashChanges = Rx.Observable.fromEvent(window, 'hashchange');
```

Is there a particular use-case this doesn't work for?

**Comment by menelaos** [comment]
@blesh Yes, listening for `hashchange` doesn't work for `history.pushState` and `history.replaceState`, unfortunately.

**Comment by mattpodwysocki** [comment]
@menelaos couldn't you use `Rx.Observable.fromEvent(window, 'popstate');` in that case with using the history API?

**Comment by menelaos** [comment]
@mattpodwysocki `popstate` does not trigger when you use `pushState` or `replaceState`, so unfortunately it's not that easy.

**Comment by stuartc** [comment]
@menelaos I've had a good (so far) experience using [history](//github.com/rackt/history) and the following:

```js
var urlHistory = History.createHistory()
var url$ = Rx.Observable.create(observer => {
  urlHistory.listen(observer.onNext.bind(observer))
})

// Log location changes
url$.subscribe(location => console.log(location))
```

There might be a better way to integrate that into Rx, but the history library is pretty solid.

**Comment by menelaos** [comment]
@stuartc Thanks, I will try that.
