### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by jmale** [Reactive-Extensions/RxJS-DOM#86]
I would like a release which contains the fix for:

https://github.com/Reactive-Extensions/RxJS-DOM/issues/64

Can someone please release another version (and publish it to npm)?

**Comment by crissdev** [comment]
:+1:

**Comment by pmlarocque** [comment]
:+1: I want the fix for [#63](https://github.com/Reactive-Extensions/RxJS-DOM/issues/63) as well.

**Comment by mattpodwysocki** [comment]
@jmale done

**Comment by pmlarocque** [comment]
Thank you :+1:
