### ISSUE TITLE
Rx-DOM not found within window.Rx

### ISSUE THREAD

**Issue by mrtnbroder** [Reactive-Extensions/RxJS-DOM#87]
I've simply put my scripts like this:

```
<script src='/scripts/rx.all.min.js'></script>
<script src='/scripts/rx.dom.min.js'></script>
```

but it looks like rx.dom does not correctly export itself to pollute the `window.Rx` object.

**Comment by jmalonzo** [comment]
Hi, are you using rx.dom or Rx.DOM? Do you have a test we can look at? 

Thanks.

**Comment by mattpodwysocki** [comment]
@mrtnbroder closing as per lack of response
