### ISSUE TITLE
Ajax 'body' content is not formatted correctly

### ISSUE THREAD

**Issue by seanislegend** [Reactive-Extensions/RxJS-DOM#94]
[Per the docs](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/ajax.md), an Ajax operator's settings should allow for its 'body' property to be an object.
```
body (Object): Optional body
```

However, this appears to be incorrect as only strings are supported. My code is as follows:
```
Rx.DOM.ajax({
    body: {
        password: password,
        username: username
    },
    crossDomain: true,
    headers: {
        'content-type': 'application/x-www-form-urlencoded'
    },
    method: 'POST',
    responseType: 'json',
    url: url
})
```

**Expected outcome**:
```
Form data:
  username: 'username string',
  password: 'password string
```

**Actual outcome**:
```
Form data:
  [object Object]
```

If I modify the code to body's value to be like below, it will work.
```
body: 'username=username&password=password'
```

**Comment by mattpodwysocki** [comment]
@seanislegend fixed as per 7.0.2.  Sorry about that!

**Comment by NXTaar** [comment]
I am at Rx.DOM v7.0.3 and the issue still exists. I can't send POST requests with a body provided as an object.

Also, as to @seanislegend, it gives me this

```
Request Payload:
      [object Object]
```

**Comment by OliverJAsh** [comment]
I'm seeing the same issue here

**Comment by phixMe** [comment]
I am seeing this as well. Passing in a normal js Object yields this strange result. I have also tried stringifying the Object without success. 

Has anybody come across this recently?
Client:
```js
{
    "subject":"", 
    "body":"",
    "attachments":[],
    "recipients":[],
    "display_recipients":[
        {
            "display_name": "asdf",
            "display_type": "fdsa",
            "recipient_id": "fsd"
        }
    ]
}
```
Server:
```js
{ subject: '',
  body: '',
  attachments: '',
  recipients: '',
  display_recipients: '[object Object]' }
```

Server with stringify:
```js
 '{"subject":"sdaf","body":"","attachments":': [ { '{"display_name":"asdf","display_type":"fdsa","recipient_id":"fsd"}': '' } ] }
```

**Comment by whiteinge** [comment]
The conversion from an object requires that you [specify the Content-type header](https://github.com/Reactive-Extensions/RxJS-DOM/blob/35271e7ddd7e68838d181beae3cee696b657f7f4/src/ajax/ajax.js#L150) like in OP.
