### ISSUE TITLE
Add more events

### ISSUE THREAD

**Issue by menelaos** [Reactive-Extensions/RxJS-DOM#96]
I noticed that RxJS-DOM does not support all (standard) [events](https://developer.mozilla.org/en-US/docs/Web/Events).

Is there a reason for that or is it just a matter of writing up the corresponding documentation?

**Comment by paulpdaniels** [comment]
You can't wire them up with `fromEvent`? Could you give a specific example?

**Comment by menelaos** [comment]
Ah, please excuse my poor wording: I meant to ask why RxJS-DOM does not provide [shortcuts](https://github.com/Reactive-Extensions/RxJS-DOM/tree/master/doc#event-shortcuts) for all standard events.

**Comment by mattpodwysocki** [comment]
@menelaos that would be adding quite a bit for very little benefit for most events.  We're trying to stick with the major events for the HTML DOM that belong on such things as document, window, etc.
